---
title: "Reproducible Research with R"
author: "Dr Stefano De Sabbata<br/>School of Geography, Geology, and the Env.<br/><a href=\"mailto:s.desabbata@le.ac.uk\">s.desabbata&commat;le.ac.uk</a><br/><a href=\"https://twitter.com/maps4thought\">&commat;maps4thought</a><br/><a href=\"https://github.com/sdesabbata\">github.com/sdesabbata</a>"
output:
  ioslides_presentation:
    template: ../IOSlides/UoL_Template.html
    logo: ../IOSlides/uol_logo.png
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



## Today's topics

- What is reproducible research?
- How to do reproducible research in R
- Tools: 
    - R
    - RStudio
    - Markdown
    - Git


## What is reproducible research?

In quantitative research, an analysis or project are considered to be **reproducible** if:

- *"the data and code used to make a finding are available and they are sufficient for an independent researcher to recreate the finding."* [Christopher Gandrud, *Reproducible Research with R and R Studio*](https://www.crcpress.com/Reproducible-Research-with-R-and-R-Studio/Gandrud/p/book/9781498715379)

That is becoming more and more important in science:

- as programming and scripting are becoming integral in most disciplines
- as the amount of data increases


## Why?

In **scientific research**:

- verificability of claims through replication
- incremental work, avoid duplication

For your **working practice**:

- better working practices
    - coding
    - project structure
    - versioning
- better teamwork
- higher impact (not just results, but code, data, etc.)


## Reproducibility and software engineering

Core aspects of **software engineering** are:

- project design
- software **readibility**
- testing
- **versioning**

As programming becomes integral to research, similar necessities arise among scientists and data analyists.


## Reproducibility and "big data"

There has been a lot of discussions about **"big data"**...

- volume, velocity, variety, ...

Beyond the hype of the moment, as the **amount** and **complexity** of data increases

- the time required to replicate an analysis using point-and-click software becomes unsustainable
- room for error increases

Workflow management software (e.g., ArcGIS ModelBuilder) is one answer, reproducible research based on script languages like R is another.


## Reproducibility in GIScience

[Singleton *et al.*](https://www.tandfonline.com/doi/abs/10.1080/13658816.2015.1137579) have discussed the issue of reproducibility in GIScience, identifying the following best practices:

1. Data should be accessible within the public domain and available to researchers.
2. Software used should have open code and be scrutable.
3. Workflows should be public and link data, software, methods of analysis and presentation with discursive narrative
4. The peer review process and academic publishing should require submission of a workflow model and ideally open archiving of those materials necessary for
replication.
5. Where full reproducibility is not possible (commercial software or sensitive data) aim to adopt aspects attainable within circumstances


## R Markdown

Check out my GitHub repository [Reproducible research with R](https://sdesabbata.github.io/ReproducibleResearch/).

